seajs.config({
      alias: {
        '$': 'jquery/jquery/1.10.1/jquery',
        'jquery': 'jquery/jquery/1.10.1/jquery',
        'widget': 'arale/widget/1.1.1/widget',
        'class' : 'arale/class/1.1.0/class',
        'events' : 'arale/events/1.1.0/events',
        'base' : 'arale/base/1.1.1/base',
        'autocomplete':'arale/autocomplete/1.3.0/autocomplete',
        'textarea':'arale/autocomplete/1.3.0/textarea-complete',
        'calendar':'arale/calendar/0.9.0/calendar',
        'cookie':'arale/cookie/1.0.2/cookie',
        'detector':'arale/detector/1.2.1/detector',
        'dialog':'arale/dialog/1.2.1/dialog',
        'confirmbox':'arale/dialog/1.2.1/confirmbox',
        'easing':'arale/easing/1.0.0/easing',
        'iframe-shim':'arale/iframe-shim/1.0.2/iframe-shim',
        'messenger':'arale/messenger/1.0.2/messenger',
        'overlay':'arale/overlay/1.1.2/overlay',
        'mask':'arale/overlay/1.1.2/mask',
        'placeholder':'arale/placeholder/1.1.0/placeholder',
        'popup':'arale/popup/1.1.3/popup',
        'position':'arale/position/1.0.1/position',
        'select':'arale/select/0.9.6/select',
        'sticky':'arale/sticky/1.2.1/sticky',
        'switchable':'arale/switchable/1.0.0/switchable',
        'accordion':'arale/switchable/1.0.0/accordion',
        'carousel':'arale/switchable/1.0.0/carousel',
        'slide':'arale/switchable/1.0.0/switchable',
        'tabs':'arale/switchable/1.0.0/tabs',
        'templatable':'arale/templatable/0.9.2/templatable',
        'tip':'arale/tip/1.1.4/tip',
        'atip':'arale/tip/1.1.4/atip',
        'upload':'arale/upload/1.0.1/upload',
        'validator':'arale/validator/0.9.5/validator',
        'validator-core':'arale/validator/0.9.5/core',

        'backbone':'gallery/backbone/1.0.0/backbone',
        'underscore':'gallery/underscore/1.4.4/underscore',
        'handlebars':'gallery/handlebars/1.0.0/handlebars',
        'handlebars-runtime':'gallery/handlebars/1.0.0/runtime',
        'moment':'gallery/moment/2.0.0/moment',
        'selection':'gallery/selection/0.9.0/selection',
        'ztree':'gallery/ztree/3.5.2/ztree',

       
      },
      preload: ["jquery"],
      debug:2,
      base: '/MyWeb/resources/js'
    });